-- CREAMOS LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS ejemplo0412;
USE ejemplo0412;
-- DEFINIMOS EL MOTOR DE ALMACENAMIENTO A MYISAM
CREATE TABLE Tabla1 (
	DNI VARCHAR(9) PRIMARY KEY,
    Nombre VARCHAR(25) NOT NULL
    )ENGINE = MyISAM;
    
SHOW TABLE STATUS LIKE 'Tabla1';

-- CAMBIAMOS EL MOTOR DE ALMACENAMIENTO A INNODB
ALTER TABLE Tabla1 ENGINE = InnoDB;

SHOW TABLE STATUS LIKE 'Tabla1';

ALTER TABLE Tabla1 ENGINE = MyISAM;

SHOW TABLE STATUS LIKE 'Tabla1';

CREATE TABLE Tabla2 (
	ID_TABLA2 INT PRIMARY KEY AUTO_INCREMENT,
    FK_TABLA2 VARCHAR(9)) ENGINE = MyISAM;
    
ALTER TABLE Tabla2 ENGINE = InnODB;

SHOW TABLE STATUS LIKE 'Tabla2';
ALTER TABLE Tabla2
ADD CONSTRAINT FK_TABLA2 FOREIGN KEY (FK_TABLA2) REFERENCES Tabla1(DNI);

-- DESCRIBE LA TABLA 
DESC Tabla1;